name: Integration

on:
  pull_request:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Load .env.test file
        uses: xom9ikk/dotenv@v2
        with:
          mode: test

      - name: Install Dependencies
        run: npm ci

      - name: test:e2e
        run: npm run test:e2e:ci

      - name: test:int
        run: npm run test:int:ci

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and uploads image to Docker Hub
        run: npm run build:docker
